{% set versions = {
    "3.5.1": "9a4154163e72041dee3fdde9cb24e814625e178091a8734a6ad5375e5371b423"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "fastjet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://fastjet.fr/repo/fastjet-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make

  host:
    - python
    - boost
    - mpfr
    - gmp
    - swig
    - autoconf
    - libtool

  run:
    - python

about:
  home: "https://fastjet.fr"
  license: "GPL-2.0"
  summary: "A software package for jet finding in pp and e+e− collisions. "
  description: |
    A software package for jet finding in pp and e+e− collisions. It includes fast native implementations of many sequential recombination clustering algorithms, plugins for access to a range of cone jet finders and tools for advanced jet manipulation.

extra:
  recipe-maintainers:
    - meiyasan
